# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1335, 750)
        self.type_box = QtWidgets.QComboBox(Dialog)
        self.type_box.setGeometry(QtCore.QRect(70, 30, 101, 22))
        self.type_box.setEditable(False)
        self.type_box.setCurrentText("")
        self.type_box.setMaxVisibleItems(15)
        self.type_box.setObjectName("type_box")
        self.subtype_box = QtWidgets.QComboBox(Dialog)
        self.subtype_box.setEnabled(False)
        self.subtype_box.setGeometry(QtCore.QRect(180, 30, 101, 22))
        self.subtype_box.setEditable(False)
        self.subtype_box.setCurrentText("")
        self.subtype_box.setMaxVisibleItems(13)
        self.subtype_box.setObjectName("subtype_box")
        self.class_box = QtWidgets.QComboBox(Dialog)
        self.class_box.setEnabled(True)
        self.class_box.setGeometry(QtCore.QRect(290, 30, 101, 22))
        self.class_box.setEditable(False)
        self.class_box.setCurrentText("")
        self.class_box.setMaxVisibleItems(13)
        self.class_box.setObjectName("class_box")
        self.primary_label = QtWidgets.QLabel(Dialog)
        self.primary_label.setGeometry(QtCore.QRect(420, 20, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.primary_label.setFont(font)
        self.primary_label.setObjectName("primary_label")
        self.secondary_label = QtWidgets.QLabel(Dialog)
        self.secondary_label.setGeometry(QtCore.QRect(420, 50, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secondary_label.setFont(font)
        self.secondary_label.setObjectName("secondary_label")
        self.primarySpinBox = QtWidgets.QSpinBox(Dialog)
        self.primarySpinBox.setGeometry(QtCore.QRect(530, 20, 42, 22))
        self.primarySpinBox.setMinimum(2)
        self.primarySpinBox.setMaximum(7)
        self.primarySpinBox.setProperty("value", 4)
        self.primarySpinBox.setObjectName("primarySpinBox")
        self.secondarySpinBox = QtWidgets.QSpinBox(Dialog)
        self.secondarySpinBox.setGeometry(QtCore.QRect(530, 50, 42, 22))
        self.secondarySpinBox.setMaximum(4)
        self.secondarySpinBox.setProperty("value", 2)
        self.secondarySpinBox.setObjectName("secondarySpinBox")
        self.startButton = QtWidgets.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(250, 570, 75, 23))
        self.startButton.setObjectName("startButton")
        self.tries_label = QtWidgets.QLabel(Dialog)
        self.tries_label.setGeometry(QtCore.QRect(70, 570, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tries_label.setFont(font)
        self.tries_label.setObjectName("tries_label")
        self.triesLine = QtWidgets.QLineEdit(Dialog)
        self.triesLine.setGeometry(QtCore.QRect(170, 570, 71, 20))
        self.triesLine.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.triesLine.setFrame(True)
        self.triesLine.setCursorPosition(6)
        self.triesLine.setObjectName("triesLine")
        self.output_text = QtWidgets.QTextEdit(Dialog)
        self.output_text.setGeometry(QtCore.QRect(10, 610, 571, 121))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.output_text.setFont(font)
        self.output_text.setReadOnly(True)
        self.output_text.setObjectName("output_text")
        self.primary_label_2 = QtWidgets.QLabel(Dialog)
        self.primary_label_2.setGeometry(QtCore.QRect(70, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.primary_label_2.setFont(font)
        self.primary_label_2.setObjectName("primary_label_2")
        self.primary_label_3 = QtWidgets.QLabel(Dialog)
        self.primary_label_3.setGeometry(QtCore.QRect(180, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.primary_label_3.setFont(font)
        self.primary_label_3.setObjectName("primary_label_3")
        self.primary_label_4 = QtWidgets.QLabel(Dialog)
        self.primary_label_4.setGeometry(QtCore.QRect(290, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.primary_label_4.setFont(font)
        self.primary_label_4.setObjectName("primary_label_4")
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(1090, 440, 71, 23))
        self.saveButton.setObjectName("saveButton")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 90, 581, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 170, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(180, 170, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(260, 170, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(310, 170, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(350, 170, 31, 16))
        self.label_5.setToolTip("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(400, 170, 51, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(110, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.max_line_1 = QtWidgets.QLineEdit(Dialog)
        self.max_line_1.setGeometry(QtCore.QRect(300, 190, 41, 20))
        self.max_line_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_1.setReadOnly(True)
        self.max_line_1.setObjectName("max_line_1")
        self.multi_line_1 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_1.setGeometry(QtCore.QRect(350, 190, 31, 20))
        self.multi_line_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_1.setReadOnly(True)
        self.multi_line_1.setObjectName("multi_line_1")
        self.reroll_check_1 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_1.setEnabled(True)
        self.reroll_check_1.setGeometry(QtCore.QRect(410, 190, 16, 16))
        self.reroll_check_1.setText("")
        self.reroll_check_1.setCheckable(True)
        self.reroll_check_1.setChecked(True)
        self.reroll_check_1.setObjectName("reroll_check_1")
        self.affix_box_1 = QtWidgets.QComboBox(Dialog)
        self.affix_box_1.setGeometry(QtCore.QRect(140, 190, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_1.sizePolicy().hasHeightForWidth())
        self.affix_box_1.setSizePolicy(sizePolicy)
        self.affix_box_1.setEditable(False)
        self.affix_box_1.setCurrentText("")
        self.affix_box_1.setMaxVisibleItems(15)
        self.affix_box_1.setObjectName("affix_box_1")
        self.special_check_1 = QtWidgets.QCheckBox(Dialog)
        self.special_check_1.setGeometry(QtCore.QRect(120, 190, 16, 16))
        self.special_check_1.setText("")
        self.special_check_1.setObjectName("special_check_1")
        self.min_line_1 = QtWidgets.QLineEdit(Dialog)
        self.min_line_1.setGeometry(QtCore.QRect(250, 190, 41, 20))
        self.min_line_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_1.setReadOnly(True)
        self.min_line_1.setObjectName("min_line_1")
        self.affix_box_2 = QtWidgets.QComboBox(Dialog)
        self.affix_box_2.setGeometry(QtCore.QRect(140, 220, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_2.sizePolicy().hasHeightForWidth())
        self.affix_box_2.setSizePolicy(sizePolicy)
        self.affix_box_2.setEditable(False)
        self.affix_box_2.setCurrentText("")
        self.affix_box_2.setMaxVisibleItems(15)
        self.affix_box_2.setObjectName("affix_box_2")
        self.reroll_check_2 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_2.setEnabled(True)
        self.reroll_check_2.setGeometry(QtCore.QRect(410, 220, 16, 16))
        self.reroll_check_2.setText("")
        self.reroll_check_2.setChecked(True)
        self.reroll_check_2.setObjectName("reroll_check_2")
        self.min_line_2 = QtWidgets.QLineEdit(Dialog)
        self.min_line_2.setGeometry(QtCore.QRect(250, 220, 41, 20))
        self.min_line_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_2.setReadOnly(True)
        self.min_line_2.setObjectName("min_line_2")
        self.special_check_2 = QtWidgets.QCheckBox(Dialog)
        self.special_check_2.setGeometry(QtCore.QRect(120, 220, 16, 16))
        self.special_check_2.setText("")
        self.special_check_2.setObjectName("special_check_2")
        self.max_line_2 = QtWidgets.QLineEdit(Dialog)
        self.max_line_2.setGeometry(QtCore.QRect(300, 220, 41, 20))
        self.max_line_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_2.setReadOnly(True)
        self.max_line_2.setObjectName("max_line_2")
        self.multi_line_2 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_2.setGeometry(QtCore.QRect(350, 220, 31, 20))
        self.multi_line_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_2.setReadOnly(True)
        self.multi_line_2.setObjectName("multi_line_2")
        self.affix_box_3 = QtWidgets.QComboBox(Dialog)
        self.affix_box_3.setGeometry(QtCore.QRect(140, 250, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_3.sizePolicy().hasHeightForWidth())
        self.affix_box_3.setSizePolicy(sizePolicy)
        self.affix_box_3.setEditable(False)
        self.affix_box_3.setCurrentText("")
        self.affix_box_3.setMaxVisibleItems(15)
        self.affix_box_3.setObjectName("affix_box_3")
        self.reroll_check_3 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_3.setEnabled(True)
        self.reroll_check_3.setGeometry(QtCore.QRect(410, 250, 16, 16))
        self.reroll_check_3.setText("")
        self.reroll_check_3.setChecked(True)
        self.reroll_check_3.setObjectName("reroll_check_3")
        self.min_line_3 = QtWidgets.QLineEdit(Dialog)
        self.min_line_3.setGeometry(QtCore.QRect(250, 250, 41, 20))
        self.min_line_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_3.setReadOnly(True)
        self.min_line_3.setObjectName("min_line_3")
        self.special_check_3 = QtWidgets.QCheckBox(Dialog)
        self.special_check_3.setGeometry(QtCore.QRect(120, 250, 16, 16))
        self.special_check_3.setText("")
        self.special_check_3.setObjectName("special_check_3")
        self.max_line_3 = QtWidgets.QLineEdit(Dialog)
        self.max_line_3.setGeometry(QtCore.QRect(300, 250, 41, 20))
        self.max_line_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_3.setReadOnly(True)
        self.max_line_3.setObjectName("max_line_3")
        self.multi_line_3 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_3.setGeometry(QtCore.QRect(350, 250, 31, 20))
        self.multi_line_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_3.setReadOnly(True)
        self.multi_line_3.setObjectName("multi_line_3")
        self.affix_box_4 = QtWidgets.QComboBox(Dialog)
        self.affix_box_4.setGeometry(QtCore.QRect(140, 280, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_4.sizePolicy().hasHeightForWidth())
        self.affix_box_4.setSizePolicy(sizePolicy)
        self.affix_box_4.setEditable(False)
        self.affix_box_4.setCurrentText("")
        self.affix_box_4.setMaxVisibleItems(15)
        self.affix_box_4.setObjectName("affix_box_4")
        self.reroll_check_4 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_4.setEnabled(True)
        self.reroll_check_4.setGeometry(QtCore.QRect(410, 280, 16, 16))
        self.reroll_check_4.setText("")
        self.reroll_check_4.setChecked(True)
        self.reroll_check_4.setObjectName("reroll_check_4")
        self.min_line_4 = QtWidgets.QLineEdit(Dialog)
        self.min_line_4.setGeometry(QtCore.QRect(250, 280, 41, 20))
        self.min_line_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_4.setReadOnly(True)
        self.min_line_4.setObjectName("min_line_4")
        self.special_check_4 = QtWidgets.QCheckBox(Dialog)
        self.special_check_4.setGeometry(QtCore.QRect(120, 280, 16, 16))
        self.special_check_4.setText("")
        self.special_check_4.setObjectName("special_check_4")
        self.max_line_4 = QtWidgets.QLineEdit(Dialog)
        self.max_line_4.setGeometry(QtCore.QRect(300, 280, 41, 20))
        self.max_line_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_4.setReadOnly(True)
        self.max_line_4.setObjectName("max_line_4")
        self.multi_line_4 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_4.setGeometry(QtCore.QRect(350, 280, 31, 20))
        self.multi_line_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_4.setReadOnly(True)
        self.multi_line_4.setObjectName("multi_line_4")
        self.affix_box_5 = QtWidgets.QComboBox(Dialog)
        self.affix_box_5.setEnabled(False)
        self.affix_box_5.setGeometry(QtCore.QRect(140, 310, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_5.sizePolicy().hasHeightForWidth())
        self.affix_box_5.setSizePolicy(sizePolicy)
        self.affix_box_5.setEditable(False)
        self.affix_box_5.setCurrentText("")
        self.affix_box_5.setMaxVisibleItems(15)
        self.affix_box_5.setObjectName("affix_box_5")
        self.reroll_check_5 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_5.setEnabled(False)
        self.reroll_check_5.setGeometry(QtCore.QRect(410, 310, 16, 16))
        self.reroll_check_5.setText("")
        self.reroll_check_5.setChecked(True)
        self.reroll_check_5.setObjectName("reroll_check_5")
        self.min_line_5 = QtWidgets.QLineEdit(Dialog)
        self.min_line_5.setEnabled(False)
        self.min_line_5.setGeometry(QtCore.QRect(250, 310, 41, 20))
        self.min_line_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_5.setReadOnly(True)
        self.min_line_5.setObjectName("min_line_5")
        self.special_check_5 = QtWidgets.QCheckBox(Dialog)
        self.special_check_5.setEnabled(False)
        self.special_check_5.setGeometry(QtCore.QRect(120, 310, 16, 16))
        self.special_check_5.setText("")
        self.special_check_5.setObjectName("special_check_5")
        self.max_line_5 = QtWidgets.QLineEdit(Dialog)
        self.max_line_5.setEnabled(False)
        self.max_line_5.setGeometry(QtCore.QRect(300, 310, 41, 20))
        self.max_line_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_5.setReadOnly(True)
        self.max_line_5.setObjectName("max_line_5")
        self.multi_line_5 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_5.setEnabled(False)
        self.multi_line_5.setGeometry(QtCore.QRect(350, 310, 31, 20))
        self.multi_line_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_5.setReadOnly(True)
        self.multi_line_5.setObjectName("multi_line_5")
        self.affix_box_6 = QtWidgets.QComboBox(Dialog)
        self.affix_box_6.setEnabled(False)
        self.affix_box_6.setGeometry(QtCore.QRect(140, 340, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_6.sizePolicy().hasHeightForWidth())
        self.affix_box_6.setSizePolicy(sizePolicy)
        self.affix_box_6.setEditable(False)
        self.affix_box_6.setCurrentText("")
        self.affix_box_6.setMaxVisibleItems(15)
        self.affix_box_6.setObjectName("affix_box_6")
        self.reroll_check_6 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_6.setEnabled(False)
        self.reroll_check_6.setGeometry(QtCore.QRect(410, 340, 16, 16))
        self.reroll_check_6.setText("")
        self.reroll_check_6.setChecked(True)
        self.reroll_check_6.setObjectName("reroll_check_6")
        self.min_line_6 = QtWidgets.QLineEdit(Dialog)
        self.min_line_6.setEnabled(False)
        self.min_line_6.setGeometry(QtCore.QRect(250, 340, 41, 20))
        self.min_line_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_6.setReadOnly(True)
        self.min_line_6.setObjectName("min_line_6")
        self.special_check_6 = QtWidgets.QCheckBox(Dialog)
        self.special_check_6.setEnabled(False)
        self.special_check_6.setGeometry(QtCore.QRect(120, 340, 16, 16))
        self.special_check_6.setText("")
        self.special_check_6.setObjectName("special_check_6")
        self.max_line_6 = QtWidgets.QLineEdit(Dialog)
        self.max_line_6.setEnabled(False)
        self.max_line_6.setGeometry(QtCore.QRect(300, 340, 41, 20))
        self.max_line_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_6.setReadOnly(True)
        self.max_line_6.setObjectName("max_line_6")
        self.multi_line_6 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_6.setEnabled(False)
        self.multi_line_6.setGeometry(QtCore.QRect(350, 340, 31, 20))
        self.multi_line_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_6.setReadOnly(True)
        self.multi_line_6.setObjectName("multi_line_6")
        self.affix_box_7 = QtWidgets.QComboBox(Dialog)
        self.affix_box_7.setEnabled(False)
        self.affix_box_7.setGeometry(QtCore.QRect(140, 370, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_7.sizePolicy().hasHeightForWidth())
        self.affix_box_7.setSizePolicy(sizePolicy)
        self.affix_box_7.setEditable(False)
        self.affix_box_7.setCurrentText("")
        self.affix_box_7.setMaxVisibleItems(15)
        self.affix_box_7.setObjectName("affix_box_7")
        self.reroll_check_7 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_7.setEnabled(False)
        self.reroll_check_7.setGeometry(QtCore.QRect(410, 370, 16, 16))
        self.reroll_check_7.setText("")
        self.reroll_check_7.setChecked(True)
        self.reroll_check_7.setObjectName("reroll_check_7")
        self.min_line_7 = QtWidgets.QLineEdit(Dialog)
        self.min_line_7.setEnabled(False)
        self.min_line_7.setGeometry(QtCore.QRect(250, 370, 41, 20))
        self.min_line_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_7.setReadOnly(True)
        self.min_line_7.setObjectName("min_line_7")
        self.special_check_7 = QtWidgets.QCheckBox(Dialog)
        self.special_check_7.setEnabled(False)
        self.special_check_7.setGeometry(QtCore.QRect(120, 370, 16, 16))
        self.special_check_7.setText("")
        self.special_check_7.setObjectName("special_check_7")
        self.max_line_7 = QtWidgets.QLineEdit(Dialog)
        self.max_line_7.setEnabled(False)
        self.max_line_7.setGeometry(QtCore.QRect(300, 370, 41, 20))
        self.max_line_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_7.setReadOnly(True)
        self.max_line_7.setObjectName("max_line_7")
        self.multi_line_7 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_7.setEnabled(False)
        self.multi_line_7.setGeometry(QtCore.QRect(350, 370, 31, 20))
        self.multi_line_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_7.setReadOnly(True)
        self.multi_line_7.setObjectName("multi_line_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(110, 390, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.multi_line_8 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_8.setGeometry(QtCore.QRect(350, 420, 31, 20))
        self.multi_line_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_8.setReadOnly(True)
        self.multi_line_8.setObjectName("multi_line_8")
        self.special_check_8 = QtWidgets.QCheckBox(Dialog)
        self.special_check_8.setGeometry(QtCore.QRect(120, 420, 16, 16))
        self.special_check_8.setText("")
        self.special_check_8.setObjectName("special_check_8")
        self.max_line_8 = QtWidgets.QLineEdit(Dialog)
        self.max_line_8.setGeometry(QtCore.QRect(300, 420, 41, 20))
        self.max_line_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_8.setReadOnly(True)
        self.max_line_8.setObjectName("max_line_8")
        self.min_line_8 = QtWidgets.QLineEdit(Dialog)
        self.min_line_8.setGeometry(QtCore.QRect(250, 420, 41, 20))
        self.min_line_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_8.setReadOnly(True)
        self.min_line_8.setObjectName("min_line_8")
        self.reroll_check_8 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_8.setEnabled(True)
        self.reroll_check_8.setGeometry(QtCore.QRect(410, 420, 16, 16))
        self.reroll_check_8.setText("")
        self.reroll_check_8.setChecked(True)
        self.reroll_check_8.setObjectName("reroll_check_8")
        self.affix_box_8 = QtWidgets.QComboBox(Dialog)
        self.affix_box_8.setGeometry(QtCore.QRect(140, 420, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_8.sizePolicy().hasHeightForWidth())
        self.affix_box_8.setSizePolicy(sizePolicy)
        self.affix_box_8.setEditable(False)
        self.affix_box_8.setCurrentText("")
        self.affix_box_8.setMaxVisibleItems(15)
        self.affix_box_8.setObjectName("affix_box_8")
        self.multi_line_9 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_9.setGeometry(QtCore.QRect(350, 450, 31, 20))
        self.multi_line_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_9.setReadOnly(True)
        self.multi_line_9.setObjectName("multi_line_9")
        self.special_check_9 = QtWidgets.QCheckBox(Dialog)
        self.special_check_9.setGeometry(QtCore.QRect(120, 450, 16, 16))
        self.special_check_9.setText("")
        self.special_check_9.setObjectName("special_check_9")
        self.max_line_9 = QtWidgets.QLineEdit(Dialog)
        self.max_line_9.setGeometry(QtCore.QRect(300, 450, 41, 20))
        self.max_line_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_9.setReadOnly(True)
        self.max_line_9.setObjectName("max_line_9")
        self.min_line_9 = QtWidgets.QLineEdit(Dialog)
        self.min_line_9.setGeometry(QtCore.QRect(250, 450, 41, 20))
        self.min_line_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_9.setReadOnly(True)
        self.min_line_9.setObjectName("min_line_9")
        self.reroll_check_9 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_9.setEnabled(True)
        self.reroll_check_9.setGeometry(QtCore.QRect(410, 450, 16, 16))
        self.reroll_check_9.setText("")
        self.reroll_check_9.setChecked(True)
        self.reroll_check_9.setObjectName("reroll_check_9")
        self.affix_box_9 = QtWidgets.QComboBox(Dialog)
        self.affix_box_9.setGeometry(QtCore.QRect(140, 450, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_9.sizePolicy().hasHeightForWidth())
        self.affix_box_9.setSizePolicy(sizePolicy)
        self.affix_box_9.setEditable(False)
        self.affix_box_9.setCurrentText("")
        self.affix_box_9.setMaxVisibleItems(15)
        self.affix_box_9.setObjectName("affix_box_9")
        self.multi_line_10 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_10.setEnabled(False)
        self.multi_line_10.setGeometry(QtCore.QRect(350, 480, 31, 20))
        self.multi_line_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_10.setReadOnly(True)
        self.multi_line_10.setObjectName("multi_line_10")
        self.special_check_10 = QtWidgets.QCheckBox(Dialog)
        self.special_check_10.setEnabled(False)
        self.special_check_10.setGeometry(QtCore.QRect(120, 480, 16, 16))
        self.special_check_10.setText("")
        self.special_check_10.setObjectName("special_check_10")
        self.max_line_10 = QtWidgets.QLineEdit(Dialog)
        self.max_line_10.setEnabled(False)
        self.max_line_10.setGeometry(QtCore.QRect(300, 480, 41, 20))
        self.max_line_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_10.setReadOnly(True)
        self.max_line_10.setObjectName("max_line_10")
        self.min_line_10 = QtWidgets.QLineEdit(Dialog)
        self.min_line_10.setEnabled(False)
        self.min_line_10.setGeometry(QtCore.QRect(250, 480, 41, 20))
        self.min_line_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_10.setReadOnly(True)
        self.min_line_10.setObjectName("min_line_10")
        self.reroll_check_10 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_10.setEnabled(False)
        self.reroll_check_10.setGeometry(QtCore.QRect(410, 480, 16, 16))
        self.reroll_check_10.setText("")
        self.reroll_check_10.setChecked(True)
        self.reroll_check_10.setObjectName("reroll_check_10")
        self.affix_box_10 = QtWidgets.QComboBox(Dialog)
        self.affix_box_10.setEnabled(False)
        self.affix_box_10.setGeometry(QtCore.QRect(140, 480, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_10.sizePolicy().hasHeightForWidth())
        self.affix_box_10.setSizePolicy(sizePolicy)
        self.affix_box_10.setEditable(False)
        self.affix_box_10.setCurrentText("")
        self.affix_box_10.setMaxVisibleItems(15)
        self.affix_box_10.setObjectName("affix_box_10")
        self.multi_line_11 = QtWidgets.QLineEdit(Dialog)
        self.multi_line_11.setEnabled(False)
        self.multi_line_11.setGeometry(QtCore.QRect(350, 510, 31, 20))
        self.multi_line_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.multi_line_11.setReadOnly(True)
        self.multi_line_11.setObjectName("multi_line_11")
        self.special_check_11 = QtWidgets.QCheckBox(Dialog)
        self.special_check_11.setEnabled(False)
        self.special_check_11.setGeometry(QtCore.QRect(120, 510, 16, 16))
        self.special_check_11.setText("")
        self.special_check_11.setObjectName("special_check_11")
        self.max_line_11 = QtWidgets.QLineEdit(Dialog)
        self.max_line_11.setEnabled(False)
        self.max_line_11.setGeometry(QtCore.QRect(300, 510, 41, 20))
        self.max_line_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.max_line_11.setReadOnly(True)
        self.max_line_11.setObjectName("max_line_11")
        self.min_line_11 = QtWidgets.QLineEdit(Dialog)
        self.min_line_11.setEnabled(False)
        self.min_line_11.setGeometry(QtCore.QRect(250, 510, 41, 20))
        self.min_line_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.min_line_11.setReadOnly(True)
        self.min_line_11.setObjectName("min_line_11")
        self.reroll_check_11 = QtWidgets.QCheckBox(Dialog)
        self.reroll_check_11.setEnabled(False)
        self.reroll_check_11.setGeometry(QtCore.QRect(410, 510, 16, 16))
        self.reroll_check_11.setText("")
        self.reroll_check_11.setChecked(True)
        self.reroll_check_11.setObjectName("reroll_check_11")
        self.affix_box_11 = QtWidgets.QComboBox(Dialog)
        self.affix_box_11.setEnabled(False)
        self.affix_box_11.setGeometry(QtCore.QRect(140, 510, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affix_box_11.sizePolicy().hasHeightForWidth())
        self.affix_box_11.setSizePolicy(sizePolicy)
        self.affix_box_11.setEditable(False)
        self.affix_box_11.setCurrentText("")
        self.affix_box_11.setMaxVisibleItems(15)
        self.affix_box_11.setObjectName("affix_box_11")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(170, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(860, 60, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.saved_text = QtWidgets.QTextEdit(Dialog)
        self.saved_text.setGeometry(QtCore.QRect(650, 540, 661, 191))
        self.saved_text.setReadOnly(True)
        self.saved_text.setObjectName("saved_text")
        self.desired_affix_1 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_1.setGeometry(QtCore.QRect(860, 150, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_1.sizePolicy().hasHeightForWidth())
        self.desired_affix_1.setSizePolicy(sizePolicy)
        self.desired_affix_1.setEditable(False)
        self.desired_affix_1.setCurrentText("")
        self.desired_affix_1.setMaxVisibleItems(15)
        self.desired_affix_1.setObjectName("desired_affix_1")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(900, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.desired_min_1 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_1.setGeometry(QtCore.QRect(970, 150, 41, 20))
        self.desired_min_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_1.setObjectName("desired_min_1")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(980, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(1030, 130, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.desired_multi_1 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_1.setGeometry(QtCore.QRect(1020, 150, 41, 20))
        self.desired_multi_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_1.setObjectName("desired_multi_1")
        self.desired_multi_2 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_2.setGeometry(QtCore.QRect(1020, 180, 41, 20))
        self.desired_multi_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_2.setObjectName("desired_multi_2")
        self.desired_affix_2 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_2.setGeometry(QtCore.QRect(860, 180, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_2.sizePolicy().hasHeightForWidth())
        self.desired_affix_2.setSizePolicy(sizePolicy)
        self.desired_affix_2.setEditable(False)
        self.desired_affix_2.setCurrentText("")
        self.desired_affix_2.setMaxVisibleItems(15)
        self.desired_affix_2.setObjectName("desired_affix_2")
        self.desired_min_2 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_2.setGeometry(QtCore.QRect(970, 180, 41, 20))
        self.desired_min_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_2.setObjectName("desired_min_2")
        self.desired_multi_3 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_3.setGeometry(QtCore.QRect(1020, 210, 41, 20))
        self.desired_multi_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_3.setObjectName("desired_multi_3")
        self.desired_affix_3 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_3.setGeometry(QtCore.QRect(860, 210, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_3.sizePolicy().hasHeightForWidth())
        self.desired_affix_3.setSizePolicy(sizePolicy)
        self.desired_affix_3.setEditable(False)
        self.desired_affix_3.setCurrentText("")
        self.desired_affix_3.setMaxVisibleItems(15)
        self.desired_affix_3.setObjectName("desired_affix_3")
        self.desired_min_3 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_3.setGeometry(QtCore.QRect(970, 210, 41, 20))
        self.desired_min_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_3.setObjectName("desired_min_3")
        self.desired_multi_4 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_4.setGeometry(QtCore.QRect(1020, 240, 41, 20))
        self.desired_multi_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_4.setObjectName("desired_multi_4")
        self.desired_affix_4 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_4.setGeometry(QtCore.QRect(860, 240, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_4.sizePolicy().hasHeightForWidth())
        self.desired_affix_4.setSizePolicy(sizePolicy)
        self.desired_affix_4.setEditable(False)
        self.desired_affix_4.setCurrentText("")
        self.desired_affix_4.setMaxVisibleItems(15)
        self.desired_affix_4.setObjectName("desired_affix_4")
        self.desired_min_4 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_4.setGeometry(QtCore.QRect(970, 240, 41, 20))
        self.desired_min_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_4.setObjectName("desired_min_4")
        self.desired_multi_5 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_5.setEnabled(False)
        self.desired_multi_5.setGeometry(QtCore.QRect(1020, 270, 41, 20))
        self.desired_multi_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_5.setObjectName("desired_multi_5")
        self.desired_affix_5 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_5.setEnabled(False)
        self.desired_affix_5.setGeometry(QtCore.QRect(860, 270, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_5.sizePolicy().hasHeightForWidth())
        self.desired_affix_5.setSizePolicy(sizePolicy)
        self.desired_affix_5.setEditable(False)
        self.desired_affix_5.setCurrentText("")
        self.desired_affix_5.setMaxVisibleItems(15)
        self.desired_affix_5.setObjectName("desired_affix_5")
        self.desired_min_5 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_5.setEnabled(False)
        self.desired_min_5.setGeometry(QtCore.QRect(970, 270, 41, 20))
        self.desired_min_5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_5.setObjectName("desired_min_5")
        self.desired_multi_6 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_6.setEnabled(False)
        self.desired_multi_6.setGeometry(QtCore.QRect(1020, 300, 41, 20))
        self.desired_multi_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_6.setObjectName("desired_multi_6")
        self.desired_affix_6 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_6.setEnabled(False)
        self.desired_affix_6.setGeometry(QtCore.QRect(860, 300, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_6.sizePolicy().hasHeightForWidth())
        self.desired_affix_6.setSizePolicy(sizePolicy)
        self.desired_affix_6.setEditable(False)
        self.desired_affix_6.setCurrentText("")
        self.desired_affix_6.setMaxVisibleItems(15)
        self.desired_affix_6.setObjectName("desired_affix_6")
        self.desired_min_6 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_6.setEnabled(False)
        self.desired_min_6.setGeometry(QtCore.QRect(970, 300, 41, 20))
        self.desired_min_6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_6.setObjectName("desired_min_6")
        self.desired_multi_7 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_7.setEnabled(False)
        self.desired_multi_7.setGeometry(QtCore.QRect(1020, 330, 41, 20))
        self.desired_multi_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_7.setObjectName("desired_multi_7")
        self.desired_affix_7 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_7.setEnabled(False)
        self.desired_affix_7.setGeometry(QtCore.QRect(860, 330, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_7.sizePolicy().hasHeightForWidth())
        self.desired_affix_7.setSizePolicy(sizePolicy)
        self.desired_affix_7.setEditable(False)
        self.desired_affix_7.setCurrentText("")
        self.desired_affix_7.setMaxVisibleItems(15)
        self.desired_affix_7.setObjectName("desired_affix_7")
        self.desired_min_7 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_7.setEnabled(False)
        self.desired_min_7.setGeometry(QtCore.QRect(970, 330, 41, 20))
        self.desired_min_7.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_7.setObjectName("desired_min_7")
        self.desired_multi_8 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_8.setGeometry(QtCore.QRect(1020, 380, 41, 20))
        self.desired_multi_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_8.setObjectName("desired_multi_8")
        self.desired_affix_8 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_8.setGeometry(QtCore.QRect(860, 380, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_8.sizePolicy().hasHeightForWidth())
        self.desired_affix_8.setSizePolicy(sizePolicy)
        self.desired_affix_8.setEditable(False)
        self.desired_affix_8.setCurrentText("")
        self.desired_affix_8.setMaxVisibleItems(15)
        self.desired_affix_8.setObjectName("desired_affix_8")
        self.desired_min_8 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_8.setGeometry(QtCore.QRect(970, 380, 41, 20))
        self.desired_min_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_8.setObjectName("desired_min_8")
        self.desired_multi_9 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_9.setGeometry(QtCore.QRect(1020, 410, 41, 20))
        self.desired_multi_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_9.setObjectName("desired_multi_9")
        self.desired_affix_9 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_9.setGeometry(QtCore.QRect(860, 410, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_9.sizePolicy().hasHeightForWidth())
        self.desired_affix_9.setSizePolicy(sizePolicy)
        self.desired_affix_9.setEditable(False)
        self.desired_affix_9.setCurrentText("")
        self.desired_affix_9.setMaxVisibleItems(15)
        self.desired_affix_9.setObjectName("desired_affix_9")
        self.desired_min_9 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_9.setGeometry(QtCore.QRect(970, 410, 41, 20))
        self.desired_min_9.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_9.setObjectName("desired_min_9")
        self.desired_multi_10 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_10.setEnabled(False)
        self.desired_multi_10.setGeometry(QtCore.QRect(1020, 440, 41, 20))
        self.desired_multi_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_10.setObjectName("desired_multi_10")
        self.desired_affix_10 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_10.setEnabled(False)
        self.desired_affix_10.setGeometry(QtCore.QRect(860, 440, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_10.sizePolicy().hasHeightForWidth())
        self.desired_affix_10.setSizePolicy(sizePolicy)
        self.desired_affix_10.setEditable(False)
        self.desired_affix_10.setCurrentText("")
        self.desired_affix_10.setMaxVisibleItems(15)
        self.desired_affix_10.setObjectName("desired_affix_10")
        self.desired_min_10 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_10.setEnabled(False)
        self.desired_min_10.setGeometry(QtCore.QRect(970, 440, 41, 20))
        self.desired_min_10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_10.setObjectName("desired_min_10")
        self.desired_multi_11 = QtWidgets.QLineEdit(Dialog)
        self.desired_multi_11.setEnabled(False)
        self.desired_multi_11.setGeometry(QtCore.QRect(1020, 470, 41, 20))
        self.desired_multi_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_multi_11.setObjectName("desired_multi_11")
        self.desired_affix_11 = QtWidgets.QComboBox(Dialog)
        self.desired_affix_11.setEnabled(False)
        self.desired_affix_11.setGeometry(QtCore.QRect(860, 470, 101, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desired_affix_11.sizePolicy().hasHeightForWidth())
        self.desired_affix_11.setSizePolicy(sizePolicy)
        self.desired_affix_11.setEditable(False)
        self.desired_affix_11.setCurrentText("")
        self.desired_affix_11.setMaxVisibleItems(15)
        self.desired_affix_11.setObjectName("desired_affix_11")
        self.desired_min_11 = QtWidgets.QLineEdit(Dialog)
        self.desired_min_11.setEnabled(False)
        self.desired_min_11.setGeometry(QtCore.QRect(970, 470, 41, 20))
        self.desired_min_11.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.desired_min_11.setObjectName("desired_min_11")
        self.clearButton = QtWidgets.QPushButton(Dialog)
        self.clearButton.setGeometry(QtCore.QRect(1090, 470, 71, 23))
        self.clearButton.setObjectName("clearButton")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(860, 110, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(860, 350, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(580, 10, 20, 731))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 540, 581, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ancient_check = QtWidgets.QCheckBox(Dialog)
        self.ancient_check.setGeometry(QtCore.QRect(1080, 150, 70, 17))
        self.ancient_check.setObjectName("ancient_check")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(650, 510, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(350, 150, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(1030, 110, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_19.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setLineWidth(2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(10, 120, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_20.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_20.setLineWidth(2)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(760, 70, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_21.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_21.setLineWidth(2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(10, 550, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 1, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_22.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_22.setLineWidth(2)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")

        self.retranslateUi(Dialog)
        self.type_box.setCurrentIndex(-1)
        self.subtype_box.setCurrentIndex(-1)
        self.class_box.setCurrentIndex(-1)
        self.affix_box_1.setCurrentIndex(-1)
        self.affix_box_2.setCurrentIndex(-1)
        self.affix_box_3.setCurrentIndex(-1)
        self.affix_box_4.setCurrentIndex(-1)
        self.affix_box_5.setCurrentIndex(-1)
        self.affix_box_6.setCurrentIndex(-1)
        self.affix_box_7.setCurrentIndex(-1)
        self.affix_box_8.setCurrentIndex(-1)
        self.affix_box_9.setCurrentIndex(-1)
        self.affix_box_10.setCurrentIndex(-1)
        self.affix_box_11.setCurrentIndex(-1)
        self.desired_affix_1.setCurrentIndex(-1)
        self.desired_affix_2.setCurrentIndex(-1)
        self.desired_affix_3.setCurrentIndex(-1)
        self.desired_affix_4.setCurrentIndex(-1)
        self.desired_affix_5.setCurrentIndex(-1)
        self.desired_affix_6.setCurrentIndex(-1)
        self.desired_affix_7.setCurrentIndex(-1)
        self.desired_affix_8.setCurrentIndex(-1)
        self.desired_affix_9.setCurrentIndex(-1)
        self.desired_affix_10.setCurrentIndex(-1)
        self.desired_affix_11.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Item constructor"))
        self.primary_label.setText(_translate("Dialog", "Primary affixes"))
        self.secondary_label.setText(_translate("Dialog", "Secondary affixes"))
        self.startButton.setText(_translate("Dialog", "Simulate"))
        self.tries_label.setText(_translate("Dialog", "Number of tries"))
        self.triesLine.setText(_translate("Dialog", "100000"))
        self.primary_label_2.setText(_translate("Dialog", "Item type"))
        self.primary_label_3.setText(_translate("Dialog", "Item subtype"))
        self.primary_label_4.setText(_translate("Dialog", "Class"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.label.setText(_translate("Dialog", "special"))
        self.label_2.setText(_translate("Dialog", "affix"))
        self.label_3.setText(_translate("Dialog", "min"))
        self.label_4.setText(_translate("Dialog", "max"))
        self.label_5.setText(_translate("Dialog", "multi"))
        self.label_6.setText(_translate("Dialog", "rerollable"))
        self.label_7.setText(_translate("Dialog", "Primary"))
        self.label_8.setText(_translate("Dialog", "Secondary"))
        self.label_9.setText(_translate("Dialog", "Item description"))
        self.label_10.setText(_translate("Dialog", "Desired stats"))
        self.label_11.setText(_translate("Dialog", "affix"))
        self.desired_min_1.setText(_translate("Dialog", "0"))
        self.label_12.setText(_translate("Dialog", "min"))
        self.label_13.setText(_translate("Dialog", "multi"))
        self.desired_multi_1.setText(_translate("Dialog", "0"))
        self.desired_multi_2.setText(_translate("Dialog", "0"))
        self.desired_min_2.setText(_translate("Dialog", "0"))
        self.desired_multi_3.setText(_translate("Dialog", "0"))
        self.desired_min_3.setText(_translate("Dialog", "0"))
        self.desired_multi_4.setText(_translate("Dialog", "0"))
        self.desired_min_4.setText(_translate("Dialog", "0"))
        self.desired_multi_5.setText(_translate("Dialog", "0"))
        self.desired_min_5.setText(_translate("Dialog", "0"))
        self.desired_multi_6.setText(_translate("Dialog", "0"))
        self.desired_min_6.setText(_translate("Dialog", "0"))
        self.desired_multi_7.setText(_translate("Dialog", "0"))
        self.desired_min_7.setText(_translate("Dialog", "0"))
        self.desired_multi_8.setText(_translate("Dialog", "0"))
        self.desired_min_8.setText(_translate("Dialog", "0"))
        self.desired_multi_9.setText(_translate("Dialog", "0"))
        self.desired_min_9.setText(_translate("Dialog", "0"))
        self.desired_multi_10.setText(_translate("Dialog", "0"))
        self.desired_min_10.setText(_translate("Dialog", "0"))
        self.desired_multi_11.setText(_translate("Dialog", "0"))
        self.desired_min_11.setText(_translate("Dialog", "0"))
        self.clearButton.setText(_translate("Dialog", "Clear saved"))
        self.label_14.setText(_translate("Dialog", "Primary"))
        self.label_15.setText(_translate("Dialog", "Secondary"))
        self.ancient_check.setText(_translate("Dialog", "Ancient"))
        self.label_16.setText(_translate("Dialog", "Desired configurations"))
        self.label_17.setToolTip(_translate("Dialog", "<html><head/><body><p>This value is used for stats that can roll in different variants.</p><p>For example: %Elemental damamge, %Skill damage, single elemental resist</p><p>For special stats that can be rerolled into another type of that stat you need to set this value, for all other stats just leave it at one.</p></body></html>"))
        self.label_17.setText(_translate("Dialog", "?"))
        self.label_18.setToolTip(_translate("Dialog", "<html><head/><body><p>Here you put minimum required &quot;multi&quot; value.</p><p>For all non-multi stats just leave it at zero or one.</p><p>For multi stats, if you want only 1 possible variation of this stat put this equal to max, for example 4 for elemental damage on DH means you only want 1 elemental type</p><p>This is the most common use case, but sometimes you are okay with either of 2 variants, then you put 3 here (for instance Impale DH where either cold or lightning is fine)</p><p>If you put in more than max (or more than 1 for regular stats), this means that this stat can\'t roll naturally and must be enchanted (%arcane on SLW, off-class mainstat)</p></body></html>"))
        self.label_18.setText(_translate("Dialog", "?"))
        self.label_19.setText(_translate("Dialog", "1"))
        self.label_20.setText(_translate("Dialog", "2"))
        self.label_21.setText(_translate("Dialog", "3"))
        self.label_22.setText(_translate("Dialog", "4"))

